[package]
name = "imagetools"
version = "0.1.0"
description = "Image Tools desktop app"
authors = ["Image Tools"]
edition = "2021"

[lib]
name = "imagetools_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "imagetools"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
url = "2"
