[package]
name = "imagetools"
version = "0.2.0"
description = "Image Tools desktop app"
authors = ["Image Tools"]
edition = "2021"

[[bin]]
name = "imagetools"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
url = "2"
serde_json = "1"
